name: spealth_flutter
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^3.0.4
  flutter_facebook_login: ^1.1.1
  flutter_svg: ^0.6.3
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/7.png
    - assets/images/8.png
    - assets/images/9.png
    - assets/icons/food.png
    - assets/icons/foodapple.png
    - assets/icons/settings.png
    - assets/icons/facebook_icon.svg
    - assets/icons/google_icon.svg

  fonts:
    - family: Courgette
      fonts:
        - asset: assets/fonts/courgette.ttf
    - family: Palatino
      fonts:
        - asset: assets/fonts/palatino.ttf